services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    container_name: beesure_postgres_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-beesure}
      POSTGRES_USER: ${POSTGRES_USER:-beesure_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0.11
    container_name: beesure_mongodb_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-beesure}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db

  spark-master:
    image: apache/spark:4.0.0-java21-python3
    container_name: spark-master
    command: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master" ]
    ports:
      - "7077:7077"
      - "8083:8080"
    volumes:
      - ./data:/opt/spark/data
      - ./logs/sparkmaster:/opt/spark/logs

  spark-worker-1:
    image: apache/spark:4.0.0-java21-python3
    container_name: spark-worker-1
    hostname: spark-worker-1
    command: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077" ]
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/opt/spark/data
      - ./logs/spark-worker-1:/opt/spark/logs

  spark-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.spark
    container_name: spark-app
    hostname: spark-app
    depends_on:
      - spark-master
      - spark-worker-1
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    stdin_open: true
    tty: true
    volumes:
      - ./data:/opt/spark/data
      - ./logs/spark-app:/opt/spark/logs
    command: "/bin/bash"


volumes:
  postgres_dev_data:
  mongodb_dev_data: